
version: '2'
services:

    pg:
        image: postgres:9.6.1
        container_name: libertyrp-pg
        ports:
            - "5432:5432"
        # volumes:
        #     - ".data/pg:/var/lib/postgresql/data"
        environment:
            POSTGRES_PASSWORD: 19216801
            POSTGRES_DB: libertyrp
            POSTGRES_USER: libertyrp
            POSTGRES_INITDB_ARGS: -A trust
